before_install:
  - sudo add-apt-repository -y ppa:fkrull/deadsnakes
install:
  - sudo apt-get install python3.3
  - virtualenv --python=python3.3 python3.3
  - python --version
script:
  - nosetests
